spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/taco?characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: adm
      password: P!ssw0rd
    url: jdbc:mysql://localhost:3306/taco?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: adm
    password: P!ssw0rd



mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    root: debug
